"use strict";
'use client';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FaucetTabSkeleton = FaucetTabSkeleton;
const jsx_runtime_1 = require("react/jsx-runtime");
const CustomSketelon_1 = __importDefault(require("../../../common/components/CustomSketelon.js"));
function FaucetTabSkeleton() {
    return ((0, jsx_runtime_1.jsx)("div", { className: "w-full flex justify-center relative pt-[24px] pb-[56px]", children: (0, jsx_runtime_1.jsx)("div", { className: "w-full flex flex-col md:flex-row  justify-center relative", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col md:flex-row md:space-x-10", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex md:flex-col md:min-w-[150px] rounded-lg space-y-1", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[56px] px-1 py-4 border-b border-default text-left flex items-center space-x-2" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[56px] px-1 py-4 border-b border-default text-left flex items-center space-x-2" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[56px] px-1 py-4 border-b border-default text-left flex items-center space-x-2" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[56px] px-1 py-4 border-b border-default text-left flex items-center space-x-2" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full md:w-[500px] large:w-[44.44vw] max-w-[800px] bg-surface-default rounded-4xl p-4 md:p-10 m-0 space-y-2", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[70%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[20%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[44px] rounded-4xl w w-[60%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[60%]" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex space-x-1", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[44px] rounded-xl w w-[80%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[44px] rounded-4xl w w-[20%]" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex pt-8", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-2 w-full", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[70%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[20%]" })] }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[44px] rounded-4xl w w-[20%]" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-2 w-full pt-8", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[70%]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-[26px] w-[20%]" })] })] })] }) }) }));
}
