export type LoginMethod = 'Email' | 'Google' | 'Facebook' | 'Apple' | 'Metamask' | 'OKX' | 'BSC' | 'WalletConnect';
export declare const usePostLogin: () => {
    afterLoginRef: import("react").MutableRefObject<({ res, account, userInfo, invitationCode, sharingBotCode, sharingWidgetCode, sharingArticleCode, sharingForumCode, sharingRoomCode, sharingBabelBotCode, inviteLink, sharingBotUid, sharingBotId, closeModal, from, loginMethod, shareWidgetLink }: {
        res: any;
        account?: any;
        userInfo?: any;
        invitationCode?: string;
        sharingBotCode?: string;
        sharingWidgetCode?: string;
        sharingArticleCode?: string;
        sharingForumCode?: string;
        sharingRoomCode?: string;
        sharingBabelBotCode?: string;
        inviteLink?: string;
        sharingBotUid?: string;
        sharingBotId?: string;
        closeModal?: () => void;
        from: string;
        loginMethod: LoginMethod;
        shareWidgetLink?: string;
    }) => Promise<void>>;
    getDataFromStorage: () => {
        sharingBotCode: string;
        sharingWidgetCode: string;
        sharingArticleCode: string;
        sharingForumCode: string;
        sharingRoomCode: string;
        sharingBabelBotCode: string;
        sharingBotId: string;
        tgGuid: string | undefined;
        inviteLink: string;
        shareWidgetLink: string;
    };
    loading: boolean;
    setLoading: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    afterLogin: ({ res, account, userInfo, invitationCode, sharingBotCode, sharingWidgetCode, sharingArticleCode, sharingForumCode, sharingRoomCode, sharingBabelBotCode, inviteLink, sharingBotUid, sharingBotId, closeModal, from, loginMethod, shareWidgetLink }: {
        res: any;
        account?: any;
        userInfo?: any;
        invitationCode?: string;
        sharingBotCode?: string;
        sharingWidgetCode?: string;
        sharingArticleCode?: string;
        sharingForumCode?: string;
        sharingRoomCode?: string;
        sharingBabelBotCode?: string;
        inviteLink?: string;
        sharingBotUid?: string;
        sharingBotId?: string;
        closeModal?: () => void;
        from: string;
        loginMethod: LoginMethod;
        shareWidgetLink?: string;
    }) => Promise<void>;
};
