import { DropzoneInputProps, DropzoneRootProps } from 'react-dropzone';
import { DisplayMessage, DraftMessage, LocalErrorMessage, Message, ServerMessage, TranslationStatus } from '../model/definitions';
import { LocalDraftMsg, MapKey, PartialMessageDetail } from '../services/useNewChatStore';
export type MessageContextProps = {
    messageMap: Map<string, DisplayMessage>;
    exceptionsForTextDisplay?: Record<MapKey, string[]>;
    addTextDisplayException?: (msgId: string) => void;
    sendTextMessage: (text: string) => void;
    sendAudioMessage: (audioBlob: Blob, mimeType?: string) => Promise<void>;
    terminate?: () => void;
    messageIdList: string[];
    lastUserInteractionId?: string;
    sending: boolean;
    interacting: boolean;
    scrollToBottom: number;
    draftMessage?: LocalDraftMsg;
    setDraftMessage: (localDraftMsg: LocalDraftMsg) => void;
    hasMore: boolean;
    gettingHistory: boolean;
    getHistoryMessage: () => Promise<ServerMessage[]>;
    addMessage: (messages: (Message | DraftMessage | LocalErrorMessage) | Array<Message | DraftMessage | LocalErrorMessage>) => void;
    updateMessage?: (message: Message | LocalErrorMessage) => void;
    deleteSpecifiedMessageId?: (msgId?: string) => void;
    partialUpdateMessage?: (messageId: string, partialDetail: PartialMessageDetail) => void;
    translationStatus?: TranslationStatus;
    translate?: (messageId: string) => void;
    playingAudio?: string;
    playNext?: () => void;
    enQueue?: (messageId: string) => void;
    clearQueue?: () => void;
    getJobInfo?: (jobId: string, messageId: string) => Promise<boolean>;
    clearMemory?: () => Promise<void>;
    getClickRootProps?: <T extends DropzoneRootProps>(props?: T) => T;
    getDragRootProps?: <T extends DropzoneRootProps>(props?: T) => T;
    getInputProps?: <T extends DropzoneInputProps>(props?: T) => T;
};
export declare const MessageContext: import("react").Context<MessageContextProps>;
