// Generated by Wrangler by running `wrangler types`

interface Env {
  MY_APP: KVNamespace;
  OPENAI_BASE_URL: 'https://aihubmix.com/v1';
  HUANYUAN_BASE_URL: 'https://api.hunyuan.cloud.tencent.com/v1';
  LIC: string;
  OPENAI_KEY: string;
  CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
  HUNYUAN_API_KEY: string;
  TECENT_CLOUD_SECRET_ID: string;
  TECENT_CLOUD_SECRET_KEY: string;
  DB_MYSHELL_RUN_TEST: D1Database;
}
