"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = EditorSkeleton;
const jsx_runtime_1 = require("react/jsx-runtime");
const PlusCircleIcon_1 = __importDefault(require("@heroicons/react/24/outline/esm/PlusCircleIcon"));
const skeleton_1 = require("../../../../common/components/ui/skeleton");
function EditorSkeleton() {
    return ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsxs)("div", { className: "hidden md:flex w-full flex-col px-6 py-4 gap-1 h-fit shrink-0", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "w-full h-9" }), (0, jsx_runtime_1.jsx)("div", { className: "w-full flex items-center justify-between", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex w-full justify-between items-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex gap-1", children: [0, 1].map(item => ((0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "size-9 rounded-full" }, item))) }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "size-9 rounded-full" })] }) })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex md:hidden w-full px-0 py-3 flex-col shrink-0 h-fit", children: (0, jsx_runtime_1.jsxs)("div", { className: "w-full bg-surface-default flex flex-col gap-2", children: [(0, jsx_runtime_1.jsx)("div", { className: "px-4", children: (0, jsx_runtime_1.jsxs)("div", { className: "p-2 w-full h-10 overflow-hidden border border-default rounded-lg shadow-textarea flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)("span", { className: "grow" }), (0, jsx_runtime_1.jsx)(PlusCircleIcon_1.default, { className: "size-7 shrink-0 text-brand opacity-30" })] }) }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full flex justify-between items-center px-4", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-[6px]", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "size-8 rounded-lg shrink-0" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-6 w-20" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex gap-1", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "size-9 rounded-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "size-9 rounded-full" })] })] })] }) })] }));
}
