import React from 'react';
type onClickFunc = (event: any) => void;
interface ImageSetItem {
    srcSet: string;
    media: string;
}
export interface Item {
    bulletClass?: string;
    bulletOnClick?: () => void;
    original: string;
    originalHeight?: string | number;
    originalWidth?: string | number;
    loading?: 'eager' | 'lazy' | undefined;
    thumbnailHeight?: string | number;
    thumbnailWidth?: string | number;
    thumbnailLoading?: 'eager' | 'lazy' | undefined;
    fullscreen?: string;
    originalAlt?: string;
    thumbnail?: string;
    thumbnailAlt?: string;
    originalClass?: string;
    thumbnailClass?: string;
    renderItem?: (item: Item) => void;
    renderThumbInner?: (item: Item) => void;
    imageSet?: ImageSetType;
    srcSet?: string;
    sizes?: string;
    [key: string]: any;
}
type ImageSetType = ImageSetItem[];
interface ImageGalleryProps {
    flickThreshold?: number;
    images: Item[] | Item[][];
    showNav?: boolean;
    lazyLoad?: boolean;
    infinite?: boolean;
    showIndex?: boolean;
    showBullets?: boolean;
    bulltetPosition?: string;
    slideWrapperClass?: string;
    showThumbnails?: boolean;
    showFullscreenButton?: boolean;
    disableThumbnailScroll?: boolean;
    disableKeyDown?: boolean;
    disableSwipe?: boolean;
    disableThumbnailSwipe?: boolean;
    useBrowserFullscreen?: boolean;
    onErrorImageURL?: string;
    indexSeparator?: string;
    startIndex?: number;
    slideDuration?: number;
    slideInterval?: number;
    slideOnThumbnailOver?: boolean;
    swipeThreshold?: number;
    swipingTransitionDuration?: number;
    swipingThumbnailTransitionDuration?: number;
    onSlide?: () => void;
    onBeforeSlide?: () => void;
    onScreenChange?: () => void;
    onClick?: (event: any) => void;
    onImageLoad?: () => void;
    onImageError?: () => void;
    onTouchMove?: (event: any) => void;
    onTouchEnd?: (event: any) => void;
    onTouchStart?: (event: any) => void;
    onMouseOver?: (event: any) => void;
    onMouseLeave?: (event: any) => void;
    onBulletClick?: (event: any) => void;
    onThumbnailError?: (event: any) => void;
    onThumbnailClick?: (event: any) => void;
    onContainerClick?: () => void;
    renderCustomControls?: () => React.ReactNode;
    renderLeftNav?: (onClick: onClickFunc) => React.ReactNode | React.JSX.Element;
    renderRightNav?: (onClick: onClickFunc) => React.ReactNode | React.JSX.Element;
    renderFullscreenButton?: (onClick: onClickFunc) => React.ReactNode | React.JSX.Element;
    renderItem?: (item: Item | Item[]) => React.ReactNode | React.JSX.Element;
    renderThumbInner?: (item: Item) => React.ReactNode | React.JSX.Element;
    stopPropagation?: boolean;
    additionalClass?: string;
    useTranslate3D?: boolean;
    useWindowKeyDown?: boolean;
    renderBottom?: (index: number) => React.ReactNode | React.JSX.Element;
}
declare const ImageGallery: (props: ImageGalleryProps) => import("react/jsx-runtime").JSX.Element;
export default ImageGallery;
