import { ServerMessage } from '../../../../../../../src/chat-new/model/definitions.js';
import { EnergyInfo } from '../../../../../../../src/common/constants/interfaces/user.js';
export declare enum SocketEvent {
    TEXT_STREAM = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_TEXT",
    AUDIO_STREAM = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_VOICE_BYTES",
    ERROR = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_ERROR",
    AUDIO_FILE_UPLOADED = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_VOICE_FILE_UPLOADED",
    SENT_MESSAGE_CREATED = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_USER_SENT_MESSAGE_CREATED",
    REPLYING = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_USER_SENT_MESSAGE_REPLYING",
    REPLIED = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_USER_SENT_MESSAGE_REPLIED",
    ROBOT_VERIFICATION = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_USER_NEED_VERIFY_IS_ROBOT",
    AUDIO_FILE_DURATION_CALCULATED = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_AUDIO_FILE_DURATION_CALCULATED",
    TEXT_STREAM_END = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_TEXT_STREAM_PUSH_FINISHED",
    AUDIO_TO_TEXT_DONE = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_VOICE_TO_TEXT_DONE",
    CONSUME_ENERGY = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_USER_CONSUMED_ENERGY",
    JOB_CREATED = "MESSAGE_REPLY_GENERATION_JOB_CREATED",
    REFERENCE_SOURCE = "MESSAGE_REPLY_REFERENCE_SOURCE",
    RECOMMEND_QUESTION = "MESSAGE_REPLY_RECOMMEND_QUESTION",
    UPDATE_HISTORY_MESSAGE = "MESSAGE_REPLY_UPDATE_HISTORY_MESSAGE",
    CREATE_WHOLE_MESSAGE = "MESSAGE_REPLY_CREATE_WHOLD_MESSAGE",
    ROOM_CLOSED = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_CHANNEL_CLOSED_BY_CREATOR",
    RECEIVE_REWARDS = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_RECEIVE_REWARDS",
    NEW_MEMBER_ENTER = "MESSAGE_REPLY_SOCKET_ELEMENT_EVENT_NAME_NEW_MEMBER_ENTER"
}
export declare enum ErrorReason {
    NO_ENOUGH_ENERGY = "ERROR_REASON_USER_NOT_ENOUGH_ENERGY",
    CONVERT_VOICE_TO_MP3_FAILED = "ERROR_REASON_CONVERT_VOICE_TO_MP3_FAILED",
    CONVERT_UPLOAD_MP3_FAILED = "ERROR_REASON_CONVERT_UPLOAD_MP3_FAILED",
    CONVERT_RUN_ASR_FAILED = "ERROR_REASON_CONVERT_RUN_ASR_FAILED",
    CONVERT_CHAT_TO_BOT_FAILED = "ERROR_REASON_CONVERT_CHAT_TO_BOT_FAILED",
    INTERNAL_ERROR = "ERROR_REASON_CONVERT_INNER_ERROR"
}
export type SocketEventError = {
    reason: ErrorReason;
    message: string;
    userId: string;
};
export type SocketEventMsg = {
    id: string;
    timestamp: string;
    event: SocketEvent;
    message: ServerMessage;
    replyContent: string;
    userEnergyInfo: EnergyInfo;
    localId: string;
    chatConsumedEnergy: number;
    err: SocketEventError;
    name: string;
};
