import { NsfwEnum, VisitorEnum } from '../../../../src/common/constants/enums/user.js';
import { BotShareKeyStatsInfo, EarningDetail, EarningDetailChartData, StakeDetail, StakeRankingListData, UserStakeInfo } from '../../../../src/common/constants/interfaces/shareKey.js';
import { EnergyInfo, PremiumInfo, User, UserConnectedAccounts, UserSettings, UserTelegramDto } from '../../../../src/common/constants/interfaces/user.js';
import { LoginMethod } from '../../../../src/hooks/user/usePrivyLogin.js';
export type UserState = {
    user: User | null;
    inviteCode: string;
    invitationCount: number;
    validInvitationCount: number;
    tgValidInvitationCount: number;
    inviteLink: string;
    retriveEnergySuccess: boolean;
    energy: number;
    dailyEnergy: number;
    isEnergyOverflow: boolean;
    tgInfo: UserTelegramDto | null;
    connectedAccounts: UserConnectedAccounts | null;
    userSettingsInfo: UserSettings[];
    rewardsCenterVisited: boolean;
    forumVisited: boolean;
    tagNoticeVisited: boolean;
    flagUserFirstPublishGallery: boolean;
    flagUserFirstVisitGallery: string;
    modelConfigClicked: boolean;
    showNsfw: NsfwEnum;
    nsfwConfirmed: boolean;
    nsfwSwitch: boolean;
    isVisitor: VisitorEnum;
    token: string | null;
    shellCoins: number | null;
    frozenShellCoins: number | null;
    shareKeysBotMap: Map<string, BotShareKeyStatsInfo>;
    myStakeData: UserStakeInfo[];
    topEarnData: StakeRankingListData[];
    soarBotData: StakeRankingListData[];
    hotBotData: StakeRankingListData[];
    potentialData: StakeRankingListData[];
    turnoverData: StakeRankingListData[];
    stakeDetail: StakeDetail[];
    earningDetail: EarningDetail | null;
    earningChartData: EarningDetailChartData[];
    loginMethod: LoginMethod | undefined;
    loginTimestamp?: number;
};
type UserActions = {
    setUser(user: User): void;
    setUserInviteCode(code: string): void;
    setInvitationCount(count: number): void;
    setValidInvitationCount(count: number): void;
    setTgValidInvitationCount(count: number): void;
    setInviteLink(link: string): void;
    setEnergyInfo(data: EnergyInfo): void;
    setTgInfo(data: UserTelegramDto): void;
    setConnectedAccounts(data: UserConnectedAccounts): void;
    setUserSettingsInfo(data: UserSettings[]): void;
    clearUser: () => void;
    setIsVisitor(isVisitor: VisitorEnum): void;
    setShowNsfw(showNsfw: NsfwEnum): void;
    setToken(token: string | null): void;
    setShellCoins(coins: number): void;
    setFrozenShellCoins(coins: number): void;
    setBotShareKeyInfo(botId: string, shareKeyInfo: BotShareKeyStatsInfo): void;
    setMyStakeData(data: UserStakeInfo[]): void;
    appendMyStakeData(data: UserStakeInfo[]): void;
    setTopEarnData(data: StakeRankingListData[]): void;
    setSoarBotData(data: StakeRankingListData[]): void;
    setHotBotData(data: StakeRankingListData[]): void;
    setPotentialData(data: StakeRankingListData[]): void;
    setTurnoverData(data: StakeRankingListData[]): void;
    setStakeDetail(data: StakeDetail[]): void;
    appendStakeDetail(data: StakeDetail[]): void;
    setEarningDetail(data: EarningDetail): void;
    setEarningChartData(data: EarningDetailChartData[]): void;
    setLoginMethod(method: LoginMethod | undefined): void;
    setLoginTimestamp(timestamp: number): void;
};
type UserStore = UserState & UserActions;
type ComputedStore = {
    userId?: string;
    premiumInfo: PremiumInfo;
    isEnergyOverflow: boolean;
    rewardsCenterVisited: boolean;
    forumVisited: boolean;
    tagNoticeVisited: boolean;
    flagUserFirstPublishGallery: boolean;
    flagUserFirstVisitGallery: string;
    modelConfigClicked: boolean;
    nsfwConfirmed: boolean;
    nsfwSwitch: boolean;
    voiceCallUsed: boolean;
    videoCallUsed: boolean;
    blockChainGuruTaskOnceCompleted: boolean;
    silentPeriodConfirmed: boolean | null;
    deductionConfirmed: boolean | null;
    subscribingEarnViewed: boolean | null;
    shareKeyEarnPopupConfirmed: boolean;
    timezone?: string;
    notification: boolean;
};
export declare const useUserStore: import("zustand").UseBoundStore<Omit<Omit<Omit<import("zustand").StoreApi<UserStore>, "getState" | "getInitialState" | "subscribe" | "destroy"> & Omit<import("zustand").StoreApi<UserState & UserActions & ComputedStore>, "setState">, "setState"> & {
    setState(nextStateOrUpdater: (UserState & UserActions & ComputedStore) | Partial<UserState & UserActions & ComputedStore> | ((state: import("immer").WritableDraft<UserState & UserActions & ComputedStore>) => void), shouldReplace?: boolean | undefined): void;
}, "setState"> & {
    setState<A extends string | {
        type: string;
    }>(nextStateOrUpdater: (UserState & UserActions & ComputedStore) | Partial<UserState & UserActions & ComputedStore> | ((state: import("immer").WritableDraft<UserState & UserActions & ComputedStore>) => void), shouldReplace?: boolean | undefined, action?: A | undefined): void;
}>;
export {};
