import { Language } from '../../chat/model/interfaces';
import { InputType } from '../../chat/model/types';
import { BannerItemProps } from '../../common/components/banner/types';
import { BotInfo, TagInfo, TTSInfo } from '../../common/constants/interfaces/bot';
import { WidgetAudioStreamDetail, WidgetImageStreamDetail, WidgetInfo, WidgetMessageDetail, WidgetTextStreamDetail } from '../../common/constants/interfaces/workshop';
import { NormalCardProps, RecommendInfo } from '../../common/model/interfaces';
import { WidgetFileProps } from './chat';
type ttsMapContent = {
    content: string;
    voiceUrl?: string;
};
interface FileUpload {
    uploading: WidgetFileProps | null;
    filesMap: Record<string, WidgetFileProps[]>;
    deletedList: string[];
    alert: Record<string, WidgetFileProps[]>;
    dragModal: boolean;
}
interface Computed {
    currentUserId?: string;
}
export type WorkshopState = {
    languageList: Language[];
    ttsList: TTSInfo[];
    myVoiceList: TTSInfo[];
    pendingVoiceIds: Set<string>;
    uncheckedSet: Set<string>;
    selectedTTSId: string;
    oriForm: any;
    currentForm: any;
    editNotSave: boolean;
    noCodeCheckPassed: boolean;
    ttsContentMap: Map<string, ttsMapContent[]>;
    widgetList: any[];
    cardWidgetList: any;
    widgetFilters: TagInfo[];
    widgetName: string;
    filterValues: Record<string, string>;
    widgetPageToken: string;
    widgetDataPush: boolean;
    gettingChatWidgetList: boolean;
    chatWidgetHasMore: boolean;
    chatWidgetPageToken: string;
    sidebarWidgetList: WidgetInfo[] | null;
    gettingChatBotList: boolean;
    sidebarMyBotList: BotInfo[] | null;
    sidebarToolboxList: BotInfo[] | null;
    draftBotIds: Set<string>;
    widgetStateMap: Record<string, {
        chatList: WidgetMessageDetail[];
        chatDic: Map<string, WidgetMessageDetail>;
    }>;
    fileUpload: FileUpload;
    widgetErrorChatRecordList: any[];
    widgetInputType: InputType;
    lastWidgetInputType: InputType;
    widgetSending: boolean;
    selectedWidgetDeleteChatList: WidgetMessageDetail[];
    sentWidgetMsgIdList: Set<string>;
    widgetTextInputMap: Record<string, string>;
    computed: Computed;
    childTagsObj: Record<string, any>;
    initializeScrolled: boolean;
    poped: boolean;
    newlyAdded: boolean;
    widgetLastMessageMap: Map<string, WidgetMessageDetail>;
    widgetDriverChatId: string;
    widgetStartJobIds: string[];
    recommend: {
        banners: BannerItemProps[] | [];
        list: RecommendInfo[] | [];
    };
    tagFilters: TagInfo[];
    searchList: NormalCardProps[];
};
export type WorkshopAction = {
    setLanguageList: (list: Language[]) => void;
    setTTSList: (list: TTSInfo[]) => void;
    setMyVoiceList: (list: TTSInfo[]) => void;
    removeItemFromUncheckedSet: (id: string) => void;
    clearUncheckedSet: () => void;
    removeDeletedVoiceIdFromSet: (id: string) => void;
    setSelectedTTSId: (ttsId?: string) => void;
    setOriForm: (oriForm: any) => void;
    setCurrentForm: (currentForm: any) => void;
    setCurrentFormItem: (key: string, value: any) => void;
    setEditNotSave: () => void;
    getEditNotSave: (keys?: string[]) => boolean;
    recordTtsContent: (ttsId: string, content: string, voiceUrl?: string) => void;
    getTtsContent: (ttsId: string, content: string) => string | undefined;
    getLatestVoice: (ttsId: string) => ttsMapContent | undefined;
    resetTtsContent: () => void;
    setCardWidgetList(cardWidgets: any): void;
    setWidgetSearchList(widgets: any[]): void;
    setWidgetFilters(widgetFilter: TagInfo[]): void;
    setWidgetName(widgetName: string): void;
    setFilterValues(filterValues: Record<string, string>): void;
    getFilterValues(): void;
    setWidgetPageToken(widgetPageToken: string): void;
    setWidgetDataPush: (WidgetDataPush: boolean) => void;
    appendSidebarWidgetList: (widgetList: WidgetInfo[]) => void;
    setSidebarWidgetList: (widgetList: WidgetInfo[]) => void;
    setSidebarMyBotList: (botList: BotInfo[]) => void;
    setSidebarToolboxList: (botList: BotInfo[]) => void;
    setDraftBotIds: (botIds: Set<string> | ((botIds: Set<string>) => Set<string>)) => void;
    updateBot: (botInfo: BotInfo) => void;
    widgetUploadFiles: (widgetId: string, files: WidgetFileProps[], retry?: boolean) => void;
    deleteWidgetUploadFiles: (widgetId: string, id?: string) => void;
    widgetAddHistoryRecord(messages: WidgetMessageDetail | WidgetMessageDetail[]): void;
    updateWidgetMessage(message: WidgetMessageDetail): void;
    widgetClearAndAddHistoryRecords(widgetId: string, messages: WidgetMessageDetail[]): void;
    setWidgetInputType(type: InputType): void;
    setWidgetSending(isSending: boolean): void;
    addWidgetDeleteChat(chat: WidgetMessageDetail): void;
    clearWidgetDeleteChat(): void;
    removeWidgetHistoryRecord(messages: WidgetMessageDetail | WidgetMessageDetail[]): void;
    removeWidgetDeleteChat(message: WidgetMessageDetail): void;
    toggleWidgetAllDeleteChat(widgetId: string, isPanelImageBot: boolean): void;
    removeHistoryRecordExceptSpecifiedMessages(widgetId: string, messageIds: string[]): void;
    getWidgetLastValidInteractionMessage(widgetId: string): WidgetMessageDetail | undefined;
    setWidgetTranslatedText(message: WidgetMessageDetail): void;
    pushWidgetChatRecord(message: WidgetMessageDetail): void;
    pushWidgetMsgIdToList(msgId: string): void;
    setWidgetTextInput: (widgetId: string, text: string) => void;
    pushWidgetErrorChatRecord: (chat: any, widgetId: string) => void;
    removeWidgetErrorChatRecord: (chatId: string, widgetId: string) => void;
    addWidgetSSETextStream: (text: WidgetTextStreamDetail) => void;
    addWidgetSSEAudioStream: (audio: WidgetAudioStreamDetail) => void;
    addWidgetSSEImageStream: (images: WidgetImageStreamDetail) => void;
    receiveWidgetVoiceUrlFromSSe(voiceUrl: string, msgId: string, widgetId: string): void;
    pollingWidgetChatMsg: (message: WidgetMessageDetail) => Promise<boolean>;
    setChildTagsObj(childTagsObj: Record<string, any>): void;
    getChildTagsObj(): void;
    generateWidgetStateMap(widgetList: WidgetInfo[]): void;
    setGettingChatWidgetList(status: boolean): void;
    setGettingChatBotList(status: boolean): void;
    setChatWidgetHasMore(status: boolean): void;
    setChatWidgetPageToken(pageToken: string): void;
    markPromptWidgetAsUnlocked(widgetId: string): void;
    setInitializeScrolled(initializeScrolled: boolean): void;
    popWidgetToTop(widgetId: string): void;
    setPoped(state: boolean): void;
    setNewlyAdded(status: boolean): void;
    setWidgetDriverChatId: (chatId: string) => void;
    setWidgetStartJobIds(jobId: string, isAdd?: boolean): void;
    setWidgetFileAlert: (data: any) => void;
    showWidgetDragModal: (val: boolean) => void;
    setRecommend(recommend: {
        banners: BannerItemProps[] | [];
        list: RecommendInfo[] | [];
    }): void;
    setNoCodeCheckPassed: (pass: boolean) => void;
    setTagFilters(info: TagInfo[] | []): void;
    setSearchList(info: NormalCardProps[] | []): void;
};
type WorkshopStore = WorkshopState & WorkshopAction;
type ComputedStore = {
    hasUncheckedVoice: boolean;
    hasErrorVoice: boolean;
    hasPendingVoice: boolean;
    selectedMyVoiceItem: TTSInfo | null;
    workshopListInitialized: boolean;
};
export declare const useWorkshopStore: import("zustand").UseBoundStore<Omit<Omit<Omit<import("zustand").StoreApi<WorkshopStore>, "getState" | "getInitialState" | "subscribe" | "destroy"> & Omit<import("zustand").StoreApi<WorkshopState & WorkshopAction & ComputedStore>, "setState">, "setState"> & {
    setState(nextStateOrUpdater: (WorkshopState & WorkshopAction & ComputedStore) | Partial<WorkshopState & WorkshopAction & ComputedStore> | ((state: import("immer").WritableDraft<WorkshopState & WorkshopAction & ComputedStore>) => void), shouldReplace?: boolean | undefined): void;
}, "setState"> & {
    setState<A extends string | {
        type: string;
    }>(nextStateOrUpdater: (WorkshopState & WorkshopAction & ComputedStore) | Partial<WorkshopState & WorkshopAction & ComputedStore> | ((state: import("immer").WritableDraft<WorkshopState & WorkshopAction & ComputedStore>) => void), shouldReplace?: boolean | undefined, action?: A | undefined): void;
}>;
export {};
dReplace?: boolean | undefined, action?: A | undefined): void;
}>;
export {};
