"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkShopSettingSkeleton = WorkShopSettingSkeleton;
const jsx_runtime_1 = require("react/jsx-runtime");
const skeleton_1 = require("../../../common/components/ui/skeleton.js");
const common_helper_1 = require("../../../common/utils/common-helper.js");
function WorkShopSettingSkeleton({ isMobile = false }) {
    return ((0, jsx_runtime_1.jsx)("div", { className: "w-full h-full flex flex-col justify-center items-center", children: (0, jsx_runtime_1.jsx)("div", { className: "flex-1 flex flex-grow items-center md:px-[2.78vw] pr-0 overflow-hidden w-full css-0", children: (0, jsx_runtime_1.jsxs)("div", { className: "relative w-full h-full", children: [(0, jsx_runtime_1.jsx)("div", { className: "md:pb-6 px-0 md:px-5 w-full xl:max-w-[65%] large:max-w-[70%] md:pt-[10px] ", children: (0, jsx_runtime_1.jsx)("div", { className: "px-4 md:px-0 pt-6 md:pt-5", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col space-y-4 pb-[20px]", children: [(0, jsx_runtime_1.jsxs)("div", { id: "profile", children: [(0, jsx_runtime_1.jsx)("p", { className: "flex items-center text-[18px] md:text-[20px] leading-[1.3] font-medium", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[26px] w-[80px] rounded" }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-secondary text-sm mt-1.5", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "text-secondary text-sm mt-1.5 h-[20px] w-[200px] rounded" }) })] }), (0, jsx_runtime_1.jsxs)("div", { id: "avator", className: "flex flex-col space-y-2.5", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-sm md:text-base", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[24px] w-[80px] rounded" }) }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { animate: true, className: "rounded-full flex-shrink-0 h-[120px] w-[120px]" }), (0, jsx_runtime_1.jsx)("p", { className: "text-secondary text-sm mt-1.5", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "text-secondary text-sm mt-1.5 h-[20px] w-[200px] rounded" }) })] }), (0, jsx_runtime_1.jsx)("div", { id: "item", className: "space-y-4", children: Array(3)
                                            .fill(1)
                                            .map(() => {
                                            return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col", children: [(0, jsx_runtime_1.jsx)("p", { className: "flex items-center text-[18px] md:text-[20px] leading-[1.3] font-medium", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[24px] w-[80px] rounded" }) }), (0, jsx_runtime_1.jsx)("p", { className: "text-secondary text-sm mt-1.5 w-full", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "text-secondary text-sm mt-1.5 h-[36px] w-full rounded" }) })] }, (0, common_helper_1.generateUUID)()));
                                        }) })] }) }) }), isMobile ? null : ((0, jsx_runtime_1.jsxs)("div", { id: "previewCard", className: "hidden xl:flex flex-col pb-[20px] w-[216px] absolute top-[30px] md:right-0 xl:right-[2.6vw] rounded-[24px]", children: [(0, jsx_runtime_1.jsx)("p", { className: "flex items-center text-[12px] font-medium leading-6 mb-[12px]", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[26px] w-[80px] rounded" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "p-[16px] rounded-2xl bg-[var(--surface-create-bg)]", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex flex-col items-center justify-center w-[184px] h-[184px] bg-surface-container-default rounded-3xl mb-[12px] aspect-square overflow-hidden relative isolate", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { animate: true, className: "w-full h-full rounded-[24px]" }) }), (0, jsx_runtime_1.jsx)("div", { className: "text-[20px] leading-7 font-normal mb-[8px] line-clamp-2", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { animate: true, className: "w-[184px] h-[28px] rounded-md" }) }), (0, jsx_runtime_1.jsx)("div", { className: "flex my-2", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { animate: true, className: "w-[126px] h-[16px] rounded-md" }) }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { animate: true, className: "w-[54px] h-[10px] rounded" })] })] }))] }) }) }));
}
