import { LoginMethod } from '../../../../src/hooks/user/usePrivyLogin.js';
declare class IdentityService {
    constructor();
    getIsNewUser(): boolean;
    setIsNewUser(isNew: boolean): void;
    getIsKol(): boolean;
    setIsKol(isKol: boolean): void;
    setIsFirstToAIpp(value: boolean): void;
    getIsFirstToAIpp(): string | undefined;
    setIsViewedHowToPlay(value: boolean): void;
    getIsViewedHowToPlay(): string | undefined;
    getMySoulCount(): number;
    getUserPublicKey(): string | null;
    setUserPublicKey(value: string): void;
    getLoginMethod(): LoginMethod | null;
    getPrivyToken(): string | null;
    getToken(): string | null;
    setToken(value: string | null): void;
    getKol(): string | null;
    setKol(kol: string): void;
    getChannel(): string | null;
    setChannel(Channel: string): void;
    getLanguage(): string | null;
    setLanguage(language: string): void;
    getVersionTip(): string | null;
    setVersionTip(tip: string): void;
    getInviteCode(): string | null;
    setInviteCode(value?: string | null): void;
    getPageSearch(pageId: string): string | null;
    setPageSearch(pageId: string, value?: string | null): void;
    getFromWeb3(): string | null;
    setFromWeb3(value?: string | null): void;
    getSharingArticleCode(): string | null;
    setSharingArticleCode(value?: string | null): void;
    getSharingForumCode(): string | null;
    setSharingForumCode(value?: string | null): void;
    getSharingWidgetCode(): string | null;
    setSharingWidgetCode(value?: string | null): void;
    getSharingBotCode(): string | null;
    setSharingBotCode(value?: string | null): void;
    getSharingBabelBotCode(): string | null;
    setSharingBabelBotCode(value?: string | null): void;
    getSharingRoomCode(): string | null;
    setSharingRoomCode(value?: string): void;
    getSharingBotId(): string | null;
    setSharingBotId(value?: string | null): void;
    getRandomVisitorId(): string | null;
    setRandomVisitorId(value?: string | null): void;
    getAnonymousId(): string | null;
    setAnonymousId(value?: string | null): void;
    getSCDeviceId(): string | null;
    setSCDeviceId(value?: string | null): void;
    getUserId(): string | null;
    setUserId(value?: string): void;
    getPublicAddress(): string | null;
    setPublicAddress(value?: string | null): void;
    getYidunValidate(): string | undefined;
    setYidunValidate(validate: string): void;
    setShareWidgetLink(link?: string): void;
    getShareWidgetLink(): string | undefined;
    setInviteInfo(link: string): void;
    getInviteInfo(): string | undefined;
    removeInviteInfo(): void;
    setTgGuid(tgGuid: string): void;
    getTgGuid(): string | undefined;
    setAutoEnhanced(autoEnhanced: string): void;
    getAutoEnhanced(): string | undefined;
    setTryAdvanced(tryAdvanced: string): void;
    getTryAdvanced(): string | undefined;
    setHasPrivyMarquee(hasPrivyMarquee: string): void;
    getHasPrivyMarquee(): string | undefined;
    setUserGuide(userGuide: string): void;
    getChatDrivered(): string | undefined;
    setChatDrivered(isDriverd: string): void;
    getUserGuide(): string | undefined;
    clearTgGuid(): void;
    clearInvitationData(): void;
    setBlockChainTransactionCalled(userId: string, step: string, expireTimeStamp: number): void;
    clearBlockChainTransactionCalled(userId: string): void;
    getBlockChainTransactionCalled(): string | null;
    setBlockChainGuruStep(userId: string, step: number): void;
    getBlockChainGuruStep(): string | null;
    setBlockChainGuruHash(userId: string, hash: `0x${string}`): void;
    clearBlockChainGuruHash(userId: string): void;
    getBlockChainGuruHash(): string | null;
    getLoginPopup(): string | null;
    setLoginPopup(val: string): void;
    setTheme(value: string): void;
    getTheme(): string | null;
    setTransactionDisplaySet(set: Set<string>): void;
    setWidgetTransactionDisplaySet(set: Set<string>): void;
    getTransactionDisplaySet(): Set<string>;
    getTextInputMap(): Record<string, string>;
    getWidgetTextInputMap(): Record<string, string>;
    setTextInputMap(val: Record<string, string>): void;
    setWidgetTextInputMap(val: Record<string, string>): void;
    removeTextInputMap(): void;
    removeWidgetTextInputMap(): void;
    setFilterValues(val: Record<string, string>): void;
    getFilterValues(): Record<string, string>;
    setChildTagsObj(val: Record<string, any>): void;
    getChildTagsObj(): Record<string, any>;
    setCreateDraft(val: Record<string, any> | null): void;
    getCreateDraft(): Record<string, any> | null;
    setDontShow2FA(val: boolean): void;
    getDontShow2FA(): boolean;
    clearAll(clearInvitation?: boolean): void;
}
export declare const identityService: IdentityService;
export {};
