export declare enum EventTypes {
    DELETE_MEMORY = "DELETE_MEMORY",
    SHOW_BOT_MODAL = "SHOW_BOT_MODAL",
    SHOW_BOT_POPUP = "SHOW_BOT_POPUP",
    AWAIT_RECORD_COMPLETE = "AWAIT_RECORD_COMPLETE",
    TRANSLATE = "TRANSLATE",
    SHOW_WIDGET_MODAL = "SHOW_WIDGET_MODAL",
    SHOW_WIDGET_POPUP = "SHOW_WIDGET_POPUP",
    DELETE_WIDGET_MEMORY = "DELETE_WIDGET_MEMORY"
}
