export declare enum ShareKeyStatus {
    STATUS_UNSPECIFIED = "STATUS_UNSPECIFIED",
    STATUS_ACTIVE = "STATUS_ACTIVE",
    STATUS_DESTROYED = "STATUS_DESTROYED"
}
export declare enum ShareKeyTradeError {
    ERROR_REASON_SHELL_COIN_NOT_ENOUGH = "ERROR_REASON_SHELL_COIN_NOT_ENOUGH",
    ERROR_REASON_SHARE_KEY_PRICE_CHANGED = "ERROR_REASON_SHARE_KEY_PRICE_CHANGED",
    ERROR_REASON_SHARE_KEY_BUY_CD_PER_USER = "ERROR_REASON_SHARE_KEY_BUY_CD_PER_USER",
    ERROR_REASON_SHARE_KEY_BUY_CD_PER_USER_AND_BOT = "ERROR_REASON_SHARE_KEY_BUY_CD_PER_USER_AND_BOT",
    ERROR_REASON_SHARE_KEY_STATUS_IS_INVALID = "ERROR_REASON_SHARE_KEY_STATUS_IS_INVALID",
    ERROR_REASON_SHARE_KEY_NOT_FOUND = "ERROR_REASON_SHARE_KEY_NOT_FOUND"
}
export declare enum DataChangeStatus {
    CHANGE_STATUS_NO_CHANGE = "CHANGE_STATUS_NO_CHANGE",
    CHANGE_STATUS_INCR = "CHANGE_STATUS_INCR",
    CHANGE_STATUS_DECR = "CHANGE_STATUS_DECR"
}
export declare enum MyStakeDataOrderByEnum {
    ORDER_BY_UNSPECIFIED = "ORDER_BY_UNSPECIFIED",
    ORDER_BY_STAKE_PRICE = "ORDER_BY_STAKE_PRICE",
    ORDER_BY_STAKE_AMOUNT = "ORDER_BY_STAKE_AMOUNT",
    ORDER_BY_PER_STAKE_EARN_POINT_LAST_7_DAYS = "ORDER_BY_PER_STAKE_EARN_POINT_LAST_7_DAYS",
    ORDER_BY_PER_STAKE_EARN_POINT_YESTERDAY = "ORDER_BY_PER_STAKE_EARN_POINT_YESTERDAY",
    ORDER_BY_STAKED_SHELL_COIN_CHANGE_RATE_VS_YESTERDAY = "ORDER_BY_STAKED_SHELL_COIN_CHANGE_RATE_VS_YESTERDAY",
    ORDER_BY_USER_TOTAL_EARNED_POINTS = "ORDER_BY_USER_TOTAL_EARNED_POINTS",
    ORDER_BY_USER_STAKED_SHELL_COIN = "ORDER_BY_USER_STAKED_SHELL_COIN",
    ORDER_BY_USER_ROI = "ORDER_BY_USER_ROI"
}
export declare enum StakeEarnDataTabEnum {
    STAT_RANKING_TAB_UNSPECIFIED = "STAT_RANKING_TAB_UNSPECIFIED",
    STAT_RANKING_TAB_TOP_EARN = "STAT_RANKING_TAB_TOP_EARN",
    STAT_RANKING_TAB_TOP_ROI = "STAT_RANKING_TAB_TOP_ROI",
    STAT_RANKING_TAB_TVL = "STAT_RANKING_TAB_TVL",
    STAT_RANKING_TAB_TVL_SOAR = "STAT_RANKING_TAB_TVL_SOAR",
    STAT_RANKING_TAB_HOT_BOT = "STAT_RANKING_TAB_HOT_BOT",
    STAT_RANKING_TAB_TURN_OVER = "STAT_RANKING_TAB_TURN_OVER",
    STAT_RANKING_TAB_SOAR = "STAT_RANKING_TAB_SOAR"
}
export declare enum StakeDetailOrderByEnum {
    ORDER_BY_RANKING = "ORDER_BY_RANKING",
    ORDER_BY_TOTAL_EARN_POINT_LAST_7_DAYS = "ORDER_BY_TOTAL_EARN_POINT_LAST_7_DAYS"
}
export declare enum EarningDetailChartTimeEnum {
    SEARCH_CHART_TIME_UNSPECIFIED = "SEARCH_CHART_TIME_UNSPECIFIED",
    SEARCH_CHART_TIME_ALL_TIME = "SEARCH_CHART_TIME_ALL_TIME",
    SEARCH_CHART_TIME_7D = "SEARCH_CHART_TIME_7D",
    SEARCH_CHART_TIME_15D = "SEARCH_CHART_TIME_15D",
    SEARCH_CHART_TIME_30D = "SEARCH_CHART_TIME_30D"
}
