export declare enum TaskTypeEnum {
    SEASON_TASK_TYPE_UNSPECIFIED = "SEASON_TASK_TYPE_UNSPECIFIED",
    SEASON_TASK_TYPE_DAILY_MESSAGE = "SEASON_TASK_TYPE_DAILY_MESSAGE",
    SEASON_TASK_TYPE_DC_INTERACTION = "SEASON_TASK_TYPE_DC_INTERACTION",
    SEASON_TASK_TYPE_BLOCKCHAIN_INTERACTION = "SEASON_TASK_TYPE_BLOCKCHAIN_INTERACTION",
    SEASON_TASK_TYPE_USE_VOICE_VIDEO = "SEASON_TASK_TYPE_USE_VOICE_VIDEO",
    SEASON_TASK_TYPE_CREATE_BOT = "SEASON_TASK_TYPE_CREATE_BOT",
    SEASON_TASK_TYPE_USE_VOICE_CLONE = "SEASON_TASK_TYPE_USE_VOICE_CLONE",
    SEASON_TASK_TYPE_USE_AUTO_PROMPT = "SEASON_TASK_TYPE_USE_AUTO_PROMPT",
    SEASON_TASK_TYPE_TALK_TO_GPT4_BOT = "SEASON_TASK_TYPE_TALK_TO_GPT4_BOT",
    SEASON_TASK_TYPE_TALK_TO_BOTS = "SEASON_TASK_TYPE_TALK_TO_BOTS",
    SEASON_TASK_TALK_TO_BOT_WITH_TAG = "SEASON_TASK_TALK_TO_BOT_WITH_TAG",
    SEASON_TASK_TYPE_BOT_MASTER = "SEASON_TASK_TYPE_BOT_MASTER",
    SEASON_TASK_TYPE_MODEL_MASTER = "SEASON_TASK_TYPE_MODEL_MASTER",
    SEASON_TASK_TYPE_INVITEE_MESSAGE_LV1 = "SEASON_TASK_TYPE_INVITEE_MESSAGE_LV1",
    SEASON_TASK_TYPE_INVITEE_MESSAGE_LV2 = "SEASON_TASK_TYPE_INVITEE_MESSAGE_LV2",
    SEASON_TASK_TYPE_FANS_KEY = "SEASON_TASK_TYPE_FANS_KEY",
    SEASON_TASK_TYPE_STAKING_EXPERIENCE = "SEASON_TASK_TYPE_STAKING_EXPERIENCE",
    SEASON_TASK_TYPE_EXPERIENCE_IMAGE_BOTS = "SEASON_TASK_TYPE_EXPERIENCE_IMAGE_BOTS",
    SEASON_TASK_TYPE_PUBLIC_VOICE_INCOME = "SEASON_TASK_TYPE_PUBLIC_VOICE_INCOME",
    SEASON_TASK_TYPE_BIND_DC_ACCOUNT = "SEASON_TASK_TYPE_BIND_DC_ACCOUNT",
    SEASON_TASK_TYPE_PATRON_BADGE = "SEASON_TASK_TYPE_PATRON_BADGE",
    SEASON_TASK_TYPE_TWEET_SHARE = "SEASON_TASK_TYPE_TWEET_SHARE",
    SEASON_TASK_TYPE_SOCIAL_MEDIA_SHARE = "SEASON_TASK_TYPE_SOCIAL_MEDIA_SHARE",
    SEASON_TASK_TOP_CURVE_HOLDERS_DAILY_INCOME = "SEASON_TASK_TOP_CURVE_HOLDERS_DAILY_INCOME",
    SEASON_TASK_TYPE_LUCKY_STAR = "SEASON_TASK_TYPE_LUCKY_STAR",
    SEASON_TASK_TYPE_CURVE_PROFIT_SHARE = "SEASON_TASK_TYPE_CURVE_PROFIT_SHARE",
    SEASON_TASK_TYPE_JACKPOT = "SEASON_TASK_TYPE_JACKPOT"
}
export declare enum GolangUserTaskStatusEnum {
    SEASON_TASK_ITEM_STATUS_UNSPECIFIED = "SEASON_TASK_ITEM_STATUS_UNSPECIFIED",
    SEASON_TASK_ITEM_STATUS_IN_PROGRESS = "SEASON_TASK_ITEM_STATUS_IN_PROGRESS",
    SEASON_TASK_ITEM_STATUS_CLAIMABLE = "SEASON_TASK_ITEM_STATUS_CLAIMABLE",
    SEASON_TASK_ITEM_STATUS_CLAIMED = "SEASON_TASK_ITEM_STATUS_CLAIMED",
    SEASON_TASK_ITEM_STATUS_UNAVAILABLE = "SEASON_TASK_ITEM_STATUS_UNAVAILABLE",
    SEASON_TASK_ITEM_STATUS_MONTHLY_LIMIT_REACHED = "SEASON_TASK_ITEM_STATUS_MONTHLY_LIMIT_REACHED"
}
export declare enum PropTypeEnum {
    standardBattlePass = "standardBattlePass",
    genesisPass = "genesisPass",
    seasonBadge = "seasonBadge",
    energyPack = "energyPack",
    shellCoin = "shellCoin"
}
export declare enum GolangRewardStatusEnum {
    BACKPACK_ITEM_STATUS_UNSPECIFIED = "BACKPACK_ITEM_STATUS_UNSPECIFIED",
    BACKPACK_ITEM_STATUS_COMING_SOON = "BACKPACK_ITEM_STATUS_COMING_SOON",
    BACKPACK_ITEM_STATUS_DISABLED = "BACKPACK_ITEM_STATUS_DISABLED"
}
export declare enum PropStatusEnum {
    BACKPACK_ITEM_STATUS_UNSPECIFIED = "BACKPACK_ITEM_STATUS_UNSPECIFIED",
    BACKPACK_ITEM_STATUS_COMING_SOON = "BACKPACK_ITEM_STATUS_COMING_SOON",
    BACKPACK_ITEM_STATUS_DISABLED = "BACKPACK_ITEM_STATUS_DISABLED"
}
export declare enum OrderType {
    ORDER_SOURCE_TYPE_UNSPECIFIED = "ORDER_SOURCE_TYPE_UNSPECIFIED",
    ORDER_SOURCE_TYPE_SEASON_POINT_EXCHANGE = "ORDER_SOURCE_TYPE_SEASON_POINT_EXCHANGE",
    ORDER_SOURCE_TYPE_BADGE_EXCHANGE = "ORDER_SOURCE_TYPE_BADGE_EXCHANGE",
    ORDER_SOURCE_TYPE_BUY_SHARE_KEY = "ORDER_SOURCE_TYPE_BUY_SHARE_KEY",
    ORDER_SOURCE_TYPE_SELL_SHARE_KEY = "ORDER_SOURCE_TYPE_SELL_SHARE_KEY"
}
export declare enum OrderStatus {
    ORDER_STATUS_UNSPECIFIED = "ORDER_STATUS_UNSPECIFIED",
    ORDER_STATUS_WAITING_PAY = "ORDER_STATUS_WAITING_PAY",
    ORDER_STATUS_PAID = "ORDER_STATUS_PAID",
    ORDER_STATUS_CANCELED = "ORDER_STATUS_CANCELED"
}
export declare enum SeasonStatus {
    SEASON_STATUS_UNSPECIFIED = "SEASON_STATUS_UNSPECIFIED",
    SEASON_STATUS_ON_GOING = "SEASON_STATUS_ON_GOING",
    SEASON_STATUS_PREPARING_FOR_REWARDS = "SEASON_STATUS_PREPARING_FOR_REWARDS",
    SEASON_STATUS_REWARDS_REDEMPTION = "SEASON_STATUS_REWARDS_REDEMPTION",
    SEASON_STATUS_FINISHED = "SEASON_STATUS_FINISHED"
}
export declare enum PointTypeEnum {
    USER_POINT_TYPE_GENERAL = "USER_POINT_TYPE_GENERAL",
    USER_POINT_TYPE_ADVOCATOR = "USER_POINT_TYPE_ADVOCATOR",
    USER_POINT_TYPE_CREATOR = "USER_POINT_TYPE_CREATOR",
    USER_POINT_TYPE_INVESTOR = "USER_POINT_TYPE_INVESTOR"
}
