export declare enum FaucetTaskType {
    FAUCET_TASK_TYPE_UNSPECIFIED = "FAUCET_TASK_TYPE_UNSPECIFIED",
    FAUCET_TASK_TYPE_CLAIM_GAS = "FAUCET_TASK_TYPE_CLAIM_GAS",
    FAUCET_TASK_TYPE_CLAIM_TOKEN = "FAUCET_TASK_TYPE_CLAIM_TOKEN",
    FAUCET_TASK_TYPE_SWAP_GAS = "FAUCET_TASK_TYPE_SWAP_GAS",
    FAUCET_TASK_TYPE_SWAP_TOKEN = "FAUCET_TASK_TYPE_SWAP_TOKEN"
}
export declare enum FaucetTaskStepType {
    FAUCET_TASK_STEP_UNSPECIFIED = "FAUCET_TASK_STEP_UNSPECIFIED",
    FAUCET_TASK_STEP_CHECK_TWEET = "FAUCET_TASK_STEP_CHECK_TWEET",
    FAUCET_TASK_STEP_CLAIM = "FAUCET_TASK_STEP_CLAIM",
    FAUCET_TASK_STEP_COMPLETED = "FAUCET_TASK_STEP_COMPLETED"
}
export declare enum FaucetTaskStepStatus {
    FAUCET_TASK_STEP_STATUS_UNSPECIFIED = "FAUCET_TASK_STEP_STATUS_UNSPECIFIED",
    FAUCET_TASK_STEP_STATUS_INIT = "FAUCET_TASK_STEP_STATUS_INIT",
    FAUCET_TASK_STEP_STATUS_PROCESSING = "FAUCET_TASK_STEP_STATUS_PROCESSING",
    FAUCET_TASK_STEP_STATUS_DONE = "FAUCET_TASK_STEP_STATUS_DONE",
    FAUCET_TASK_STEP_STATUS_FAILED = "FAUCET_TASK_STEP_STATUS_FAILED"
}
export declare enum FaucetTaskStatus {
    FAUCET_TASK_STATUS_UNSPECIFIED = "FAUCET_TASK_STATUS_UNSPECIFIED",
    FAUCET_TASK_STATUS_INIT = "FAUCET_TASK_STATUS_INIT",
    FAUCET_TASK_STATUS_COMPLETED = "FAUCET_TASK_STATUS_COMPLETED"
}
export declare enum FaucetCurrency {
    FAUCET_CURRENCY_TYPE_UNSPECIFIED = "FAUCET_CURRENCY_TYPE_UNSPECIFIED",
    FAUCET_CURRENCY_TYPE_SHELL_COIN = "FAUCET_CURRENCY_TYPE_SHELL_COIN",
    FAUCET_CURRENCY_TYPE_SHELL_GAS = "FAUCET_CURRENCY_TYPE_SHELL_GAS",
    FAUCET_CURRENCY_TYPE_SHELL_TOKEN = "FAUCET_CURRENCY_TYPE_SHELL_TOKEN"
}
