export declare enum CardEnum {
    TYPE_NORMAL_TITLE = "TYPE_NORMAL_TITLE",
    TYPE_SLIDER = "TYPE_SLIDER",
    TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED"
}
export declare enum MediaEnum {
    MEDIA_TYPE_VIDEO = "MEDIA_TYPE_VIDEO",
    MEDIA_TYPE_IMAGE = "MEDIA_TYPE_IMAGE",
    MEDIA_TYPE_UNSPECIFIED = "MEDIA_TYPE_UNSPECIFIED"
}
export declare enum WidgetStatusEnum {
    STATUS_UNSPECIFIED = "STATUS_UNSPECIFIED",
    STATUS_PUBLIC = "STATUS_PUBLIC",
    STATUS_PRIVATE = "STATUS_PRIVATE"
}
export declare enum ChatPanelTypeEnum {
    BOT_CHAT_PANEL_TYPE_UNSPECIFIED = "BOT_CHAT_PANEL_TYPE_UNSPECIFIED",
    BOT_CHAT_PANEL_TYPE_IM = "BOT_CHAT_PANEL_TYPE_IM",
    BOT_CHAT_PANEL_TYPE_IMAGE_GEN = "BOT_CHAT_PANEL_TYPE_IMAGE_GEN",
    BOT_CHAT_PANEL_TYPE_COMPONENT = "BOT_CHAT_PANEL_TYPE_COMPONENT"
}
export declare enum ParamTypeEnum {
    BOT_IM_SLASH_PARAM_TYPE_UNSPECIFIED = "BOT_IM_SLASH_PARAM_TYPE_UNSPECIFIED",
    BOT_IM_SLASH_PARAM_TYPE_NUMBER = "BOT_IM_SLASH_PARAM_TYPE_NUMBER",
    BOT_IM_SLASH_PARAM_TYPE_STRING = "BOT_IM_SLASH_PARAM_TYPE_STRING"
}
export declare enum supportedEmbedTypesEnum {
    MESSAGE_METADATA_TYPE_UNSPECIFIED = "MESSAGE_METADATA_TYPE_UNSPECIFIED",
    MESSAGE_METADATA_TYPE_IMAGE_FILE = "MESSAGE_METADATA_TYPE_IMAGE_FILE",
    MESSAGE_METADATA_TYPE_TEXT_FILE = "MESSAGE_METADATA_TYPE_TEXT_FILE",
    MESSAGE_METADATA_TYPE_ALL_FILE = "MESSAGE_METADATA_TYPE_ALL_FILE",
    MESSAGE_METADATA_TYPE_AUDIO_FILE = "MESSAGE_METADATA_TYPE_AUDIO_FILE",
    MESSAGE_METADATA_TYPE_VIDEO_FILE = "MESSAGE_METADATA_TYPE_VIDEO_FILE",
    MESSAGE_METADATA_TYPE_TEXT_CONTENT = "MESSAGE_METADATA_TYPE_TEXT_CONTENT",
    MESSAGE_METADATA_TYPE_USER_AUDIO = "MESSAGE_METADATA_TYPE_USER_AUDIO",
    MESSAGE_METADATA_TYPE_COMPONENT_INPUT = "MESSAGE_METADATA_TYPE_COMPONENT_INPUT",
    MESSAGE_METADATA_TYPE_ASYNC_JOB_INFO = "MESSAGE_METADATA_TYPE_ASYNC_JOB_INFO"
}
export declare enum ImComponentsInputTypeEnum {
    BOT_IM_COMPONENT_INPUT_TYPE_UNSPECIFIED = "BOT_IM_COMPONENT_INPUT_TYPE_UNSPECIFIED",
    BOT_IM_COMPONENT_INPUT_TYPE_FILE_UPLOAD = "BOT_IM_COMPONENT_INPUT_TYPE_FILE_UPLOAD",
    BOT_IM_COMPONENT_INPUT_TYPE_VIDEO_UPLOAD = "BOT_IM_COMPONENT_INPUT_TYPE_VIDEO_UPLOAD",
    BOT_IM_COMPONENT_INPUT_TYPE_IMAGE_UPLOAD = "BOT_IM_COMPONENT_INPUT_TYPE_IMAGE_UPLOAD",
    BOT_IM_COMPONENT_INPUT_TYPE_TEXT_UPLOAD = "BOT_IM_COMPONENT_INPUT_TYPE_TEXT_UPLOAD",
    BOT_IM_COMPONENT_INPUT_TYPE_TEXT_INPUT = "BOT_IM_COMPONENT_INPUT_TYPE_TEXT_INPUT",
    BOT_IM_COMPONENT_INPUT_TYPE_TEXT_SELECTOR = "BOT_IM_COMPONENT_INPUT_TYPE_TEXT_SELECTOR",
    BOT_IM_COMPONENT_INPUT_TYPE_NUMBER_INPUT = "BOT_IM_COMPONENT_INPUT_TYPE_NUMBER_INPUT",
    BOT_IM_COMPONENT_INPUT_TYPE_INTEGER_INPUT = "BOT_IM_COMPONENT_INPUT_TYPE_INTEGER_INPUT",
    BOT_IM_COMPONENT_INPUT_TYPE_CHECKBOX = "BOT_IM_COMPONENT_INPUT_TYPE_CHECKBOX",
    BOT_IM_COMPONENT_INPUT_TYPE_NUMBER_SELECTOR = "BOT_IM_COMPONENT_INPUT_TYPE_NUMBER_SELECTOR",
    BOT_IM_COMPONENT_INPUT_TYPE_CODE_EDITOR = "BOT_IM_COMPONENT_INPUT_TYPE_NUMBER_SELECTOR"
}
export declare enum WidgetChatCallerTypeEnum {
    WIDGET_CHAT_CALLER_TYPE_UNSPECFIED = "WIDGET_CHAT_CALLER_TYPE_UNSPECFIED",
    WIDGET_CHAT_CALLER_TYPE_PROMPT = "WIDGET_CHAT_CALLER_TYPE_PROMPT",
    WIDGET_CHAT_CALLER_TYPE_VOICE = "WIDGET_CHAT_CALLER_TYPE_VOICE",
    WIDGET_CHAT_CALLER_TYPE_COMPONENT = "WIDGET_CHAT_CALLER_TYPE_COMPONENT"
}
