"use strict";
'use client';
Object.defineProperty(exports, "__esModule", { value: true });
exports.ForumDetailContentSkeleton = ForumDetailContentSkeleton;
const jsx_runtime_1 = require("react/jsx-runtime");
const skeleton_1 = require("../../../common/components/ui/skeleton.js");
const TagListSkeleton_1 = require("./TagListSkeleton.js");
function ForumDetailContentSkeleton() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "w-full space-y-4 max-w-[720px]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "w-full flex justify-between items-center", children: [(0, jsx_runtime_1.jsx)(TagListSkeleton_1.TagListSkeleton, {}), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "w-4 h-4" })] }), (0, jsx_runtime_1.jsx)("div", { className: "w-full", children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "w-[60%] h-7" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-row justify-start space-x-3", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "w-9 h-9 rounded-lg" }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col justify-center space-y-1", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-3 w-10" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-3 w-30" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full space-y-1", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-[60%]" })] }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[300px] w-full" }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full space-y-1", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-[30%]" })] }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-[300px] w-full" }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full space-y-1", children: [(0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-full" }), (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-4 w-[80%]" })] }), (0, jsx_runtime_1.jsx)("div", { children: (0, jsx_runtime_1.jsx)(skeleton_1.Skeleton, { className: "h-7 w-10" }) })] }));
}
