import { ICubismModelSetting } from 'live2d_framework/dist/icubismmodelsetting';
import { CubismIdHandle } from 'live2d_framework/dist/id/cubismid';
import { CubismMatrix44 } from 'live2d_framework/dist/math/cubismmatrix44';
import { CubismUserModel } from 'live2d_framework/dist/model/cubismusermodel';
import { ACubismMotion, FinishedMotionCallback } from 'live2d_framework/dist/motion/acubismmotion';
import { CubismMotionQueueEntryHandle } from 'live2d_framework/dist/motion/cubismmotionqueuemanager';
import { csmMap } from 'live2d_framework/dist/type/csmmap';
import { csmRect } from 'live2d_framework/dist/type/csmrectf';
import { csmString } from 'live2d_framework/dist/type/csmstring';
import { csmVector } from 'live2d_framework/dist/type/csmvector';
import * as LAppDefine from './lappdefine';
import { TextureInfo } from './lapptexturemanager';
import { LAppWavFileHandler } from './lappwavfilehandler';
export declare class LAppModel extends CubismUserModel {
    loadAssets(dir: string, fileName: string, param: LAppDefine.ModelParam): void;
    private setupModel;
    private setupTextures;
    reloadRenderer(): void;
    update(): void;
    startMotion(group: string, no: number, priority: number, onFinishedMotionHandler?: FinishedMotionCallback, audio?: ArrayBuffer): CubismMotionQueueEntryHandle;
    startRandomMotion(group: string, priority: number, onFinishedMotionHandler?: FinishedMotionCallback, audio?: ArrayBuffer): CubismMotionQueueEntryHandle;
    setExpression(expressionId: string): void;
    setRandomExpression(): void;
    motionEventFired(eventValue: csmString): void;
    hitTest(hitArenaName: string, x: number, y: number): boolean;
    preLoadMotionGroup(group: string): void;
    releaseMotions(): void;
    releaseExpressions(): void;
    doDraw(): void;
    draw(matrix: CubismMatrix44): void;
    hasMocConsistencyFromFile(): Promise<boolean | undefined>;
    constructor();
    _modelSetting: ICubismModelSetting;
    _modelHomeDir: string;
    _userTimeSeconds: number;
    _eyeBlinkIds: csmVector<CubismIdHandle>;
    _lipSyncIds: csmVector<CubismIdHandle>;
    _motions: csmMap<string, ACubismMotion>;
    _expressions: csmMap<string, ACubismMotion>;
    _hitArea: csmVector<csmRect>;
    _userArea: csmVector<csmRect>;
    _idParamAngleX: CubismIdHandle;
    _idParamAngleY: CubismIdHandle;
    _idParamAngleZ: CubismIdHandle;
    _idParamEyeBallX: CubismIdHandle;
    _idParamEyeBallY: CubismIdHandle;
    _idParamBodyAngleX: CubismIdHandle;
    _state: number;
    _expressionCount: number;
    _textureCount: number;
    _motionCount: number;
    _allMotionCount: number;
    _wavFileHandler: LAppWavFileHandler;
    _consistency: boolean;
    onLoad: (textureInfo: TextureInfo) => void;
}
