import { ChatSetting, MessageDetail } from '../../../../../src/chat/model/interfaces.js';
import { InputType } from '../../../../../src/chat/model/types.js';
import { BotInfo } from '../../../../../src/common/constants/interfaces/bot.js';
import { User } from '../../../../../src/common/constants/interfaces/user.js';
declare function ChatListRenderRow(props: {
    chat: MessageDetail;
    latest: boolean;
    downloading: boolean;
    onDownload: (filePath: string, fileName: string) => void;
    botId: string;
    selectedBot?: BotInfo | null;
    user: User | null;
    inputType: InputType;
    removeHistoryRecord: (message: MessageDetail | MessageDetail[]) => void;
    openContextmenu: () => void;
    closeContextmenu: () => void;
    clickPositionYRef: any;
    setCopyText: (text: string) => void;
    addChatID: (id: string) => void;
    removeChatID: (id: string) => void;
    sharedChatIDList: string[];
    addDeleteChat: (chat: MessageDetail) => void;
    removeDeleteChat: (chat: MessageDetail) => void;
    selectedDeleteChatList: MessageDetail[];
    isMobile?: boolean;
    botChatSetting?: ChatSetting;
    scrollToBottom: () => void;
    updateMessage: (chat: MessageDetail) => void;
    toggleImagePanelOpen: (value: any) => void;
}): import("react/jsx-runtime").JSX.Element;
declare const _default: import("react").MemoExoticComponent<typeof ChatListRenderRow>;
export default _default;
