import { RefObject } from 'react';
import { IUploadSettings } from '../../../../../src/chat/model/interfaces.js';
import { BotInfo } from '../../../../../src/common/constants/interfaces/bot.js';
type EditorInputProps = {
    onSend: (flag?: boolean) => void;
    selectedBot?: BotInfo | null;
    selectedBotId: string;
    isMobile: boolean;
    toggleImagePanelOpen: (value: any) => void;
    isWorkshop?: boolean;
    showInput: boolean;
    setShowInput: (value: boolean) => void;
    allowTextInput?: boolean;
    allowAudioInput?: boolean;
    allowUploadFile?: boolean;
    uploadSettings?: IUploadSettings;
    textInputRef: RefObject<HTMLTextAreaElement>;
    isFullScreen: boolean;
    setFullScreen: (val: boolean) => void;
};
declare function EditorInput({ onSend, selectedBot, selectedBotId, isMobile, toggleImagePanelOpen, isWorkshop, showInput, setShowInput, allowTextInput, allowAudioInput, allowUploadFile, textInputRef, uploadSettings, isFullScreen, setFullScreen }: EditorInputProps): import("react/jsx-runtime").JSX.Element;
declare const _default: import("react").MemoExoticComponent<typeof EditorInput>;
export default _default;
