import { ReactNode } from 'react';
import { ICurve } from '../../../../../../../../src/apis/apiTypes.js';
import { ChatModuleType } from '../../../../../../../../src/chat/ChatStaticContext.js';
import { AuthorInfo, LLMModel, PhotoInfo, TagInfo } from '../../../../../../../../src/common/constants/interfaces/bot.js';
import { WidgetInfo } from '../../../../../../../../src/common/constants/interfaces/workshop.js';
type ActiveContent = 'photos' | 'widgets' | 'shares';
type P = {
    type: ChatModuleType;
    active?: ActiveContent;
    id: string;
    logoUrl?: string;
    isOfficial?: boolean;
    photos?: PhotoInfo[];
    tags?: TagInfo[];
    name?: string;
    description?: string;
    author?: Pick<AuthorInfo, 'id' | 'name' | 'nameTag'>;
    tgName?: string;
    model?: LLMModel;
    curve?: ICurve;
    widgets: WidgetInfo[];
    githubUrl?: string;
    isSticky?: boolean;
    buttonSlot?: ReactNode;
    tradeSlot?: ReactNode;
    hideBottomEmpty?: boolean;
};
export default function BotDetail({ type, active, id, logoUrl, isOfficial, tags, photos, name, description, author, widgets, curve, tgName, model, githubUrl, buttonSlot, tradeSlot, isSticky, hideBottomEmpty }: P): import("react/jsx-runtime").JSX.Element;
export {};
