import { InputType } from '../../../../../src/chat/model/types.js';
import { User } from '../../../../../src/common/constants/interfaces/user.js';
import { WidgetInfo, WidgetMessageDetail } from '../../../../../src/common/constants/interfaces/workshop.js';
declare function WidgetChatListRenderRow(props: {
    chat: WidgetMessageDetail;
    latest: boolean;
    downloading: boolean;
    onDownload: (filePath: string, fileName: string) => void;
    widgetInfo?: WidgetInfo | null;
    user: User | null;
    inputType: InputType;
    removeHistoryRecord: (message: WidgetMessageDetail | WidgetMessageDetail[]) => void;
    openContextmenu: () => void;
    closeContextmenu: () => void;
    clickPositionYRef: any;
    setCopyText: (text: string) => void;
    addDeleteChat: (chat: WidgetMessageDetail) => void;
    removeDeleteChat: (chat: WidgetMessageDetail) => void;
    selectedDeleteChatList: WidgetMessageDetail[];
    isMobile?: boolean;
    scrollToBottom: () => void;
    updateMessage: (chat: WidgetMessageDetail) => void;
    toggleImagePanelOpen: (value: any) => void;
}): import("react/jsx-runtime").JSX.Element;
declare const _default: import("react").MemoExoticComponent<typeof WidgetChatListRenderRow>;
export default _default;
