'use client';
import { jsx as _jsx } from "react/jsx-runtime";
import * as PopoverPrimitive from '@radix-ui/react-popover';
import * as React from 'react';
import { cn } from '../../../../lib/utils.js';
const MTooltip = PopoverPrimitive.Root;
const MTooltipTrigger = PopoverPrimitive.Trigger;
const MTooltipArrow = PopoverPrimitive.Arrow;
const MTooltipContent = React.forwardRef(({ className, sideOffset = 4, ...props }, ref) => (_jsx(PopoverPrimitive.Portal, { children: _jsx(PopoverPrimitive.Content, { ref: ref, align: "center", side: "top", sideOffset: sideOffset, className: cn('z-50 rounded-lg border border-opaque bg-surface-default px-3 py-2 text-xs text-subtle shadow-modal-default outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2', className), ...props }) })));
MTooltipContent.displayName = PopoverPrimitive.Content.displayName;
export { MTooltip, MTooltipTrigger, MTooltipContent, MTooltipArrow };
