"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = BadgeExchangeCoinModal;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("@chakra-ui/react");
const ArrowSmallRightIcon_1 = __importDefault(require("@heroicons/react/24/outline/ArrowSmallRightIcon"));
const dayjs_1 = __importDefault(require("dayjs"));
const image_1 = __importDefault(require("next/image"));
const next_intl_1 = require("next-intl");
const next_themes_1 = require("next-themes");
const react_2 = require("react");
const CustomSketelon_1 = __importDefault(require("../../../../common/components/CustomSketelon.js"));
const common_helper_1 = require("../../../../common/utils/common-helper.js");
const reward_center_1 = require("../../../../common/utils/reward-center/index.js");
const useShellCoin_1 = __importDefault(require("../../../../hooks/user/useShellCoin.js"));
const store_1 = require("../../../../services/store/index.js");
const alphaSeasonStartDate = (0, dayjs_1.default)('2023-07-01T04:00:00Z').format('YYYY-MM-DD');
const alphaSeasonEndDate = (0, dayjs_1.default)('2023-10-16T04:00:00Z').format('YYYY-MM-DD');
function BadgeExchangeCoinModal({ isOpen, onClose, rewardInfo }) {
    const t = (0, next_intl_1.useTranslations)('reward_center.reward_redemption_content.rewards.shell_coin.badge.alpha_season_journey');
    const badgeT = (0, next_intl_1.useTranslations)('reward_center.reward_redemption_content.rewards.season_badge');
    const rT = (0, next_intl_1.useTranslations)('reward_center');
    const { resolvedTheme } = (0, next_themes_1.useTheme)();
    const { badgeToCoinExchanging, badgeToCoin, querying, getHoldBadges } = (0, useShellCoin_1.default)();
    const isDark = resolvedTheme === 'dark';
    const user = (0, store_1.useUserStore)(state => state.user);
    const holdBadges = (0, store_1.useTaskStore)(state => state.holdBadges);
    const userRegistrationDate = (0, react_2.useMemo)(() => (0, dayjs_1.default)(user?.createdDate).format('YYYY-MM-DD'), [user?.createdDate]);
    const isInRedeemablePeriod = (0, dayjs_1.default)().isBefore((0, dayjs_1.default)(rewardInfo.endDate)) && (0, dayjs_1.default)().isAfter((0, dayjs_1.default)(rewardInfo.startDate));
    const [step, setStep] = (0, react_2.useState)(1);
    (0, react_2.useEffect)(() => {
        if (isInRedeemablePeriod && !holdBadges.length) {
            getHoldBadges();
        }
    }, [holdBadges.length, isInRedeemablePeriod]);
    const handleExchange = (0, react_2.useCallback)(() => {
        badgeToCoin(holdBadges, onClose);
    }, [holdBadges]);
    const totalCoins = (0, react_2.useMemo)(() => {
        return !!holdBadges.length ? (0, common_helper_1.numberArraySum)(holdBadges.map(badge => badge.shellCoinAmount)) : 0;
    }, [holdBadges]);
    return ((0, jsx_runtime_1.jsxs)(react_1.Modal, { isOpen: isOpen, onClose: onClose, isCentered: true, size: "4xl", closeOnEsc: !badgeToCoinExchanging, closeOnOverlayClick: !badgeToCoinExchanging, children: [(0, jsx_runtime_1.jsx)(react_1.ModalOverlay, { className: "bg-white-opacity-95 dark:bg-black-opacity-95" }), (0, jsx_runtime_1.jsx)(react_1.ModalContent, { className: "rounded-4xl shadow-modal-default overflow-hidden p-0 w-full md:w-fit mx-4 md:mx-0 h-fit", children: (0, jsx_runtime_1.jsxs)(react_1.ModalBody, { className: "p-0", children: [(0, jsx_runtime_1.jsxs)("div", { className: "hidden md:flex h-[405.57px] bg-surface", children: [(0, jsx_runtime_1.jsx)("div", { className: "pr-3 w-fit", children: (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col justify-between p-6 rounded-4xl w-[334px] h-full shadow-[8px_0_12px_0_#0000000F] bg-no-repeat bg-center bg-cover", style: {
                                            backgroundImage: `${isDark
                                                ? 'radial-gradient(501.15% 215.57% at 135.03% -28.23%, rgba(0, 0, 0, 0.15) 0%, rgba(0, 0, 0, 0.30) 37.53%, rgba(0, 0, 0, 0.60) 100%)'
                                                : 'radial-gradient(392.27% 167.13% at 118.38% -17.88%, rgba(255, 255, 255, 0.00) 0%, rgba(255, 255, 255, 0.20) 37.53%, rgba(255, 255, 255, 0.80) 87.53%)'}, url(${(0, common_helper_1.getAssetsUrl)('rewards/badge_exchange/badge_exchange@2x.png')})`
                                        }, children: [(0, jsx_runtime_1.jsx)("div", { className: "text-lg font-[500] uppercase text-on-surface", children: t('title') }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4 text-[14px] leading-[22px] text-[#414345] dark:text-white", children: [(0, jsx_runtime_1.jsx)("p", { children: t('start_end', {
                                                            startDate: alphaSeasonStartDate,
                                                            endDate: alphaSeasonEndDate
                                                        }) }), (0, jsx_runtime_1.jsx)("p", { children: t('user_registration_time', {
                                                            date: userRegistrationDate
                                                        }) }), (0, jsx_runtime_1.jsx)("p", { children: t('thanks') })] })] }) }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col py-4 pl-3 pr-4 bg-surface space-y-3 relative w-[365px]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "grow space-y-4 flex flex-col overflow-hidden", children: [(0, jsx_runtime_1.jsx)("h2", { className: "shrink-0 text-on-surface text-2xl", children: t('badge_list') }), (0, jsx_runtime_1.jsx)("ul", { className: "overflow-auto no-scrollbar", children: querying
                                                        ? Array(3)
                                                            .fill(1)
                                                            .map(() => ((0, jsx_runtime_1.jsxs)("li", { className: "py-4 space-y-2 text-sm border-t border-default", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-8 rounded-[4.32px]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-6 w-24" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-x-1 flex items-center", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-5" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px] items-center", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-[16.5px] h-[16.5px] rounded-full" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-end space-x-[6px]", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-5" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-1 items-cen", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-[16.5px] h-[16.5px] rounded-full" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" })] })] })] }, (0, common_helper_1.generateUUID)())))
                                                        : holdBadges
                                                            .slice()
                                                            .sort((a, b) => {
                                                            return (Number((0, reward_center_1.getValueFromSubType)(a.userBackpackItem.item.subType)) -
                                                                Number((0, reward_center_1.getValueFromSubType)(b.userBackpackItem.item.subType)));
                                                        })
                                                            .map(badge => ((0, jsx_runtime_1.jsxs)("li", { className: "py-4 space-y-2 text-sm border-t border-default", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "season badge", src: (0, common_helper_1.getAssetsUrl)(`prop-media/nft-badge-s${(0, reward_center_1.getValueFromSubType)(badge.userBackpackItem.item.subType)}-still.png`), width: 32, height: 32, className: "rounded-[4.32px]" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[6px]", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-on-surface", children: badgeT('title', {
                                                                                                season: (0, reward_center_1.getValueFromSubType)(badge.userBackpackItem.item.subType)
                                                                                            }) }), (0, jsx_runtime_1.jsxs)("span", { className: "text-primary", children: ["x", badge.userBackpackItem.count] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-x-1 flex items-center text-[#414345] dark:text-[#B8BCCF]", children: [(0, jsx_runtime_1.jsxs)("span", { children: ["1 ", t('badge')] }), (0, jsx_runtime_1.jsx)("span", { children: "=" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px]", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/bot/photo/15388/20240119/24a777112c314c5f896a39c79dd97e83.png'), width: 16.5, height: 16.5 }), (0, jsx_runtime_1.jsx)("span", { children: badge.shellCoinPrice })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-end space-x-[6px] text-[#FAAC00]", children: [(0, jsx_runtime_1.jsx)("span", { children: t('total') }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-1 items-center", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/bot/photo/15388/20240119/24a777112c314c5f896a39c79dd97e83.png'), width: 16.5, height: 16.5 }), (0, jsx_runtime_1.jsx)("span", { children: badge.shellCoinAmount })] })] })] }, badge.userBackpackItem.item.subType))) })] }), (0, jsx_runtime_1.jsx)(react_1.Button, { variant: "unstyled", h: "44px", w: "full", className: "bg-primary space-x-[6px] shrink-0 flex items-center justify-center", color: "white", rounded: "full", px: "24px", isDisabled: querying || !totalCoins, isLoading: badgeToCoinExchanging, _hover: {
                                                _disabled: {
                                                    opacity: 0.3,
                                                    bgColor: 'var(--primary)'
                                                }
                                            }, onClick: handleExchange, children: rewardInfo.endDate && !isInRedeemablePeriod ? (rT('reward_redemption_content.available_soon')) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("span", { children: rT('reward_redemption_content.rewards.shell_coin.exchange') }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px]", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/season/ui/shell_coin.png'), width: 18.333, height: 18.333, className: "w-[18.33px] h-[18.33px] shrink-0" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm", children: totalCoins })] })] })) })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex md:hidden h-[405.57px] bg-surface", children: [step === 1 && ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col justify-between p-6 rounded-4xl h-full shadow-[8px_0_12px_0_#0000000F] bg-no-repeat bg-center bg-cover", style: {
                                        backgroundImage: `${isDark
                                            ? 'radial-gradient(501.15% 215.57% at 135.03% -28.23%, rgba(0, 0, 0, 0.15) 0%, rgba(0, 0, 0, 0.30) 37.53%, rgba(0, 0, 0, 0.60) 100%)'
                                            : 'radial-gradient(392.27% 167.13% at 118.38% -17.88%, rgba(255, 255, 255, 0.00) 0%, rgba(255, 255, 255, 0.20) 37.53%, rgba(255, 255, 255, 0.80) 87.53%)'}, url(${(0, common_helper_1.getAssetsUrl)('rewards/badge_exchange/badge_exchange@2x.png')})`
                                    }, children: [(0, jsx_runtime_1.jsx)("div", { className: "text-lg font-[500] uppercase text-on-surface", children: t('title') }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-4 text-[14px] leading-[22px] text-[#414345] dark:text-white", children: [(0, jsx_runtime_1.jsx)("p", { children: t('start_end', {
                                                        startDate: alphaSeasonStartDate,
                                                        endDate: alphaSeasonEndDate
                                                    }) }), (0, jsx_runtime_1.jsx)("p", { children: t('user_registration_time', {
                                                        date: userRegistrationDate
                                                    }) }), (0, jsx_runtime_1.jsx)("p", { children: t('thanks') })] }), (0, jsx_runtime_1.jsxs)(react_1.Button, { variant: "unstyled", h: "44px", w: "full", className: "bg-primary space-x-[6px] shrink-0 flex items-center justify-center font-[500] text-white", rounded: "full", px: "24px", onClick: () => setStep(2), children: [(0, jsx_runtime_1.jsx)("span", { children: rT('reward_redemption_content.exchange_now') }), (0, jsx_runtime_1.jsx)(ArrowSmallRightIcon_1.default, { className: "w-5 h-5" })] })] })), step === 2 && ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col p-4 bg-surface space-y-3 relative w-full h-full", children: [(0, jsx_runtime_1.jsxs)("div", { className: "grow space-y-4 flex flex-col overflow-hidden", children: [(0, jsx_runtime_1.jsx)("h2", { className: "shrink-0 text-on-surface text-2xl", children: t('badge_list') }), (0, jsx_runtime_1.jsx)("ul", { className: "overflow-auto no-scrollbar", children: querying
                                                        ? Array(3)
                                                            .fill(1)
                                                            .map(() => ((0, jsx_runtime_1.jsxs)("li", { className: "py-4 space-y-2 text-sm border-t border-default", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-8 rounded-[4.32px]" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "h-6 w-24" })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-x-1 flex items-center", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-5" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px] items-center", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-[16.5px] h-[16.5px] rounded-full" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-end space-x-[6px]", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-8 h-5" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-1 items-cen", children: [(0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-[16.5px] h-[16.5px] rounded-full" }), (0, jsx_runtime_1.jsx)(CustomSketelon_1.default, { customClass: "w-4 h-5" })] })] })] }, (0, common_helper_1.generateUUID)())))
                                                        : holdBadges
                                                            .slice()
                                                            .sort((a, b) => {
                                                            return (Number((0, reward_center_1.getValueFromSubType)(a.userBackpackItem.item.subType)) -
                                                                Number((0, reward_center_1.getValueFromSubType)(b.userBackpackItem.item.subType)));
                                                        })
                                                            .map(badge => ((0, jsx_runtime_1.jsxs)("li", { className: "py-4 space-y-2 text-sm border-t border-default", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-1", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "season badge", src: (0, common_helper_1.getAssetsUrl)(`prop-media/nft-badge-s${(0, reward_center_1.getValueFromSubType)(badge.userBackpackItem.item.subType)}-still.png`), width: 32, height: 32, className: "rounded-[4.32px]" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[6px]", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-on-surface", children: badgeT('title', {
                                                                                                season: (0, reward_center_1.getValueFromSubType)(badge.userBackpackItem.item.subType)
                                                                                            }) }), (0, jsx_runtime_1.jsxs)("span", { className: "text-primary", children: ["x", badge.userBackpackItem.count] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "space-x-1 flex items-center text-[#414345] dark:text-[#B8BCCF]", children: [(0, jsx_runtime_1.jsxs)("span", { children: ["1 ", t('badge')] }), (0, jsx_runtime_1.jsx)("span", { children: "=" }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px]", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/bot/photo/15388/20240119/24a777112c314c5f896a39c79dd97e83.png'), width: 16.5, height: 16.5 }), (0, jsx_runtime_1.jsx)("span", { children: badge.shellCoinPrice })] })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-end space-x-[6px] text-[#FAAC00]", children: [(0, jsx_runtime_1.jsx)("span", { children: t('total') }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-1 items-center", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/bot/photo/15388/20240119/24a777112c314c5f896a39c79dd97e83.png'), width: 16.5, height: 16.5 }), (0, jsx_runtime_1.jsx)("span", { children: badge.shellCoinAmount })] })] })] }, badge.userBackpackItem.item.subType))) })] }), (0, jsx_runtime_1.jsx)(react_1.Button, { variant: "unstyled", h: "44px", w: "full", className: "bg-primary space-x-[6px] shrink-0 flex items-center justify-center", color: "white", rounded: "full", px: "24px", isDisabled: querying || !totalCoins, isLoading: badgeToCoinExchanging, _hover: {
                                                _disabled: {
                                                    opacity: 0.3,
                                                    bgColor: 'var(--primary)'
                                                }
                                            }, onClick: handleExchange, children: rewardInfo.endDate && !isInRedeemablePeriod ? (rT('reward_redemption_content.available_soon')) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("span", { children: rT('reward_redemption_content.rewards.shell_coin.exchange') }), (0, jsx_runtime_1.jsxs)("span", { className: "inline-flex space-x-[2px]", children: [(0, jsx_runtime_1.jsx)(image_1.default, { alt: "shell coins", src: (0, common_helper_1.getAssetsUrlV2)('image/season/ui/shell_coin.png'), width: 18.333, height: 18.333, className: "w-[18.33px] h-[18.33px] shrink-0" }), (0, jsx_runtime_1.jsx)("span", { className: "text-sm", children: totalCoins })] })] })) })] }))] })] }) })] }));
}
