import { ChatModuleType } from '../../../../src/chat/ChatStaticContext.js';
import { DraftMessage, LocalErrorMessage, Message } from '../model/definitions';
import { LocalDraftMsg, PartialMessageDetail } from '../services/useNewChatStore';
export default function useMessageParams(type: ChatModuleType, id: string, entityId?: string, showMockReply?: boolean): {
    messageIdList: string[];
    messageMap: Map<string, Message>;
    lastMessageInfo: Message | undefined;
    lastUserInteractionMsgId: string;
    draftMessage: LocalDraftMsg;
    sending: boolean;
    interacting: boolean;
    scrollToBottom: number;
    exceptionsForTextDisplay: Record<`bot-${string}` | `widget-${string}` | `gallery-${string}` | `room-${string}` | `ugc-${string}` | `curve-${string}`, string[]>;
    addTextDisplayException: (msgId: string) => void;
    setDraftMessage: (localDraftMsg?: LocalDraftMsg) => void;
    sendTextMessage: (text: string) => void;
    sendAudioMessage: (audio: string) => void;
    sendButtonInteractionMessage: () => void;
    replaceDraftMessage: (message: Message | LocalErrorMessage) => void;
    addMessage: (messages: (Message | DraftMessage | LocalErrorMessage) | Array<Message | DraftMessage | LocalErrorMessage>) => void;
    updateMessage: (message: Message | LocalErrorMessage) => void;
    updateMsg: (message: Message | LocalErrorMessage) => void;
    addTextStream: (messageId: string, content: string) => void;
    addAudioStream: (messageId: string, audioChunk: ArrayBuffer) => void;
    addTranslationStream: (messageId: string, translation: string) => void;
    deleteSpecifiedMessageId: (msgId?: string) => void;
    partialUpdateMsg: (messageId: string, partialDetail: PartialMessageDetail) => void;
    audioQueue: {
        playingAudio: string;
        queue: string[];
        enQueue: (id: string) => void;
        clearQueue: () => void;
        playNext: () => void;
    };
};
