export declare const API_URL: string;
export declare const WS_API_URL: string | undefined;
export declare const PARTICLE_PROJECT_ID: string;
export declare const PARTICLE_APP_ID: string;
export declare const PARTICLE_CLIENT_ID: string;
export declare const WC_PROJECT_ID: string;
export declare const CDN_URL: string;
export declare const HTML2IMAGE_URL: string;
export declare const TG_BOT_NAME: string;
export declare const DISCORD_CLIENT_ID: string;
export declare const DISCORD_REDIRECT_URL: string;
export declare const TWITTER_CLIENT_ID: string;
export declare const TWITTER_REDIRECT_URL: string;
export declare const TWITTER_CODE_CHALLENGE: string;
export declare const DISABLE_GA: string;
export declare const DISABLE_ADS: string;
export declare const DATAFLUX_RUM_ID: string;
export declare const DISABLE_DATAFLUX_RUM: string;
export declare const DATAFLUX_RUM_ORIGIN: string;
export declare const CAPTCHA_ID: string;
export declare const UPDATE_REPORT_ADDRESS: string;
export declare const DISABLE_SENSORS_TRACK: string;
export declare const DISABLE_ANALYTICS: string;
export declare const SALT: string;
export declare const APP_URL: string;
export declare const SENSORS_URL: string;
export declare const NETEASE_ENGINE_APP_ID: string;
export declare const WEB3_API_URL: string;
export declare const CONTRACT_ADDRESS_STAKING: string;
export declare const SENSORS_ABTEST: string;
export declare const FIREBASE_MESSAGING_VAPID_KEY: string;
export declare const FIREBASE_MESSAGING_APIKEY: string | undefined;
export declare const FIREBASE_MESSAGING_AUTHDOMAIN: string | undefined;
export declare const FIREBASE_MESSAGING_PROJECTID: string | undefined;
export declare const FIREBASE_MESSAGING_STORAGEBUCKET: string | undefined;
export declare const FIREBASE_MESSAGING_MESSAGINGSENDERID: string | undefined;
export declare const FIREBASE_MESSAGING_APPID: string | undefined;
export declare const FIREBASE_MESSAGING_MEASUREMENTID: string | undefined;
export declare const TRANSLATOR_BOT_ID: string | undefined;
