export declare enum MessageStatusEnum {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    DONE = "DONE",
    ERROR = "ERROR",
    CANCELING = "CANCELING",
    CANCELED = "CANCELED"
}
export declare enum MessageTypeEnum {
    TEXT = "TEXT",
    VOICE = "VOICE",
    REPLY = "REPLY",
    RESET = "RESET",
    PROMPT_UPDATED = "PROMPT_UPDATED",
    GREETING = "GREETING",
    MORE_BOT_TO_EXPLORE = "MORE_BOT_TO_EXPLORER",
    NEED_TO_REGISTER = "NEED_TO_REGISTER",
    VOICE_CALL_END = "VOICE_CALL_END",
    VOICE_CALL_TEXT = "VOICE_CALL_TEXT",
    VOICE_CALL_VOICE = "VOICE_CALL_VOICE",
    VOICE_CALL_REPLY = "VOICE_CALL_REPLY",
    LLM_MODERATION_REQUEST = "LLM_MODERATION_REQUEST",
    EMBED_OBJ_STATUS_QUEUEING = "EMBED_OBJ_STATUS_QUEUEING",
    BUTTON_INTERACTION = "BUTTON_INTERACTION",
    WIDGET_PROMPT_UPDATED = "WIDGET_PROMPT_UPDATED"
}
export declare enum VoiceCallStatusEnum {
    NOT_CONNECTED = "NOT_CONNECTED",
    CONNECTING = "CONNECTING",
    CONNECTED = "CONNECTED"
}
export declare enum ModelStatusEnum {
    EMBED_OBJ_STATUS_QUEUEING = "EMBED_OBJ_STATUS_QUEUEING",
    EMBED_OBJ_STATUS_PROCESSING = "EMBED_OBJ_STATUS_PROCESSING",
    EMBED_OBJ_STATUS_DONE = "EMBED_OBJ_STATUS_DONE",
    EMBED_OBJ_STATUS_ERROR = "EMBED_OBJ_STATUS_ERROR"
}
export declare enum MessageComponentsTypeEnum {
    ROW = "BOT_MESSAGE_COMPONENTS_TYPE_ROW",
    BUTTON = "BOT_MESSAGE_COMPONENTS_TYPE_BUTTON",
    CONTAINER = "BOT_MESSAGE_COMPONENTS_TYPE_CONTAINER"
}
export declare enum MessageComponentsButtonContentDirectionEnum {
    LEFT = "BOT_MESSAGE_COMPONENTS_BUTTON_CONTENT_DIRECTION_LEFT",
    RIGHT = "BOT_MESSAGE_COMPONENTS_BUTTON_CONTENT_DIRECTION_RIGHT"
}
export declare enum MessageComponentsButtonActionTypeEnum {
    JUMP_LINK = "MESSAGE_COMPONENTS_BUTTON_ACTION_TYPE_JUMP_LINK",
    POP_UP_FORM = "MESSAGE_COMPONENTS_BUTTON_ACTION_TYPE_POP_UP_FORM",
    INTERACTION = "MESSAGE_COMPONENTS_BUTTON_ACTION_TYPE_INTERACTION",
    CLIPBOARD = "MESSAGE_COMPONENTS_BUTTON_ACTION_TYPE_CLIPBOARD"
}
export declare enum MessageComponentsButtonActionInteractionInputDisplayTypeEnum {
    TEXT = "BOT_MESSAGE_COMPONENTS_BUTTON_ACTION_INTERACTION_INPUT_DISPLAY_TYPE_TEXT",
    SLASH_COMMAND = "BOT_MESSAGE_COMPONENTS_BUTTON_ACTION_INTERACTION_INPUT_DISPLAY_TYPE_SLASH_COMMAND",
    NOTHING = "BOT_MESSAGE_COMPONENTS_BUTTON_ACTION_INTERACTION_INPUT_DISPLAY_TYPE_NOTHING"
}
export declare enum OnchainInteractionError {
    UserReject = "rejected the request",
    OnWrongChain = "does not match the target chain"
}
