name: audit

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # CYPRESS_INSTALL_BINARY: '0'
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      NX_DAEMON: 'false'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit diff
        run: |
          git diff HEAD^ HEAD --unified=0 | grep "^[+]" | grep -v "^[+][+][+]" > commit_diff.txt
          echo "查看 commit diff 的前几行："
          head -n 20 commit_diff.txt
