name: audit

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Display GitHub Run ID
        run: |
          echo "GitHub Run ID: ${{ github.run_id }}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get commit diff
        run: |
          git diff HEAD^ HEAD --unified=0 | grep "^[+]" | grep -v "^[+][+][+]" > commit_diff.txt
          echo "查看 commit diff 的前几行："
          head -n 20 commit_diff.txt
          echo "将 commit diff 发送到 webhook..."
          curl -X POST -H "Content-Type: text/plain" --data-binary @commit_diff.txt https://n8n.myshell.run/webhook/fea4ad7b-e0bd-4d06-8462-1d844410f554
